# Generated by Django 5.2.11 on 2026-02-28 09:46

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('author', models.CharField(default='Suzstar Counseling Team', max_length=200)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('excerpt', models.TextField(help_text='Brief summary for blog listings', max_length=500)),
                ('content', ckeditor.fields.RichTextField()),
                ('category', models.CharField(choices=[('anxiety', 'Anxiety & Stress'), ('depression', 'Depression & Mood'), ('relationships', 'Relationships'), ('self_care', 'Self-Care & Wellness'), ('trauma', 'Trauma & Recovery'), ('youth', 'Youth & Teen Support'), ('general', 'General Mental Health')], max_length=100)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.IntegerField(default=0)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_replied', models.BooleanField(default=False)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(help_text='e.g., Licensed Professional Counselor', max_length=200)),
                ('bio', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='counselors/')),
                ('specialties', models.CharField(help_text='Comma-separated list of specialties', max_length=500)),
                ('languages', models.CharField(default='English', help_text='Languages spoken', max_length=200)),
                ('experience_years', models.IntegerField(default=0)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('event_type', models.CharField(choices=[('workshop', 'Workshop'), ('support_group', 'Support Circle'), ('outreach', 'Community Outreach'), ('webinar', 'Webinar')], max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('location', models.CharField(max_length=500)),
                ('is_online', models.BooleanField(default=False)),
                ('online_link', models.URLField(blank=True, null=True)),
                ('max_participants', models.IntegerField(default=0, help_text='0 for unlimited')),
                ('current_participants', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', ckeditor.fields.RichTextField()),
                ('category', models.CharField(choices=[('general', 'General'), ('services', 'Services'), ('appointments', 'Appointments'), ('fees', 'Fees & Payment'), ('online', 'Online Counseling'), ('privacy', 'Privacy & Confidentiality')], max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_date', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-subscribed_date'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('resource_type', models.CharField(choices=[('article', 'Article'), ('guide', 'Guide'), ('video', 'Video'), ('exercise', 'Exercise'), ('external', 'External Link')], max_length=50)),
                ('description', models.TextField()),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='resources/')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('downloads_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('individual', 'Individual Counseling'), ('group', 'Group Therapy & Support Circles'), ('workshop', 'Psychoeducation Workshops'), ('outreach', 'Community Outreach & Awareness')], max_length=50)),
                ('short_description', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('icon_name', models.CharField(help_text="FontAwesome icon name (e.g., 'heart', 'users')", max_length=50)),
                ('price_range', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(blank=True, help_text='e.g., 45-60 minutes', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Suzstar Counseling', max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=500)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('primary_color', models.CharField(default='#4A90E2', max_length=20)),
                ('secondary_color', models.CharField(default='#F5A623', max_length=20)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Kenyan phone number (e.g., 0712345678 or +254712345678)', regex='^(\\+254|0)[7][0-9]{8}$')])),
                ('whatsapp', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True)),
                ('monday_friday', models.CharField(default='8am - 5pm', max_length=100)),
                ('saturday', models.CharField(default='8am - 12pm', max_length=100)),
                ('sunday', models.CharField(default='Closed / By appointment', max_length=100)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('meta_description', models.TextField(blank=True, max_length=300)),
                ('meta_keywords', models.CharField(blank=True, max_length=500)),
                ('google_analytics_id', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Kenyan phone number (e.g., 0712345678 or +254712345678)', regex='^(\\+254|0)[7][0-9]{8}$')])),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('appointment_type', models.CharField(choices=[('individual', 'Individual Counseling'), ('group', 'Group Therapy'), ('workshop', 'Workshop'), ('consultation', 'Initial Consultation')], max_length=50)),
                ('session_mode', models.CharField(choices=[('in_person', 'In-Person'), ('online_video', 'Online Video'), ('online_voice', 'Online Voice'), ('phone', 'Phone Call')], default='online_video', max_length=50)),
                ('concerns', models.TextField(help_text="Briefly describe what you'd like support with")),
                ('is_new_client', models.BooleanField(default=True, help_text='Is this your first time seeking counseling?')),
                ('hear_about_us', models.CharField(blank=True, help_text='How did you hear about us?', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='pending', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Admin notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.counselor')),
            ],
            options={
                'ordering': ['-preferred_date', '-preferred_time'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_initials', models.CharField(help_text="e.g., 'M.K.' for privacy", max_length=10)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('testimonial', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_received', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
